# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# this is the list of items potentially displayed
# phoenix on  feature/sc-5351/remove-serial-number-from-meters [$] via  v1.14.5 (OTP 25)
format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$elixir\
$erlang\
$lua\
$nodejs\
$memory_usage\
$aws\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

# prevents warning
# [WARN] - (starship::utils): Executing command "/Users/mmcclure/.asdf/shims/elixir" timed out.
command_timeout = 1800

# use NerdFont from Kitty to display official Elixir symbol
[elixir]
symbol = ' '

# use NerdFont from Kitty to display official git branch symbol
[git_branch]
symbol = ' '
